# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcHIkWKxK2ueN8QR5GBx-52mxRYnGlmu
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
file_path = "air_quality_traffic_weather.csv"  # Update if the path changes
df = pd.read_csv(file_path)

# Convert 'Date' to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Set the date as the index (optional but useful for time series)
df.set_index('Date', inplace=True)

# Plotting example: PM2.5, PM10 over time
plt.figure(figsize=(12, 6))
plt.plot(df.index, df['PM2.5 (µg/m³)'], label='PM2.5')
plt.plot(df.index, df['PM10 (µg/m³)'], label='PM10')
plt.xlabel('Date')
plt.ylabel('Concentration (µg/m³)')
plt.title('Air Quality Over Time')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()